name: Workflow to deploy documentation for SeqAn3

on: [push]

jobs:
  my_job:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Doxygen
        uses: ./.github/actions/setup-doxygen
        with:
          doxygen-version: 1.8.17

      - name: Setup CMake
        uses: ./.github/actions/setup-cmake
        with:
          cmake-version: 3.7.2

      - name: Diagnostics
        shell: bash
        run: |
            echo The target branch name is ${GITHUB_REF#refs/heads/}
            echo "PATH: ${PATH}"
            echo "CMAKE: `cmake --version`"
            echo "DOXYGEN: `doxygen --version`"

      # - name: Install Dependencies
      #   run: sudo apt-get install texlive-font-utils ghostscript texlive-latex-extra graphviz # graphviz for dot, latex to parse formulas
      #
      # - name: Build documentation
      #   shell: bash
      #   run: |
      #     mkdir doc-build
      #     cd doc-build
      #     cmake ../test/documentation
      #     make -j 2 doc_usr doc_dev

      # - name: Deploy User Documentation
      #   uses: Pendect/action-rsyncer@master
      #   env:
      #     DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #   with:
      #     flags: '-avzr --delete'
      #     src: 'doc-build/doc_usr/html'
      #     dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-user'
      #
      # - name: Deploy Developer Documentation
      #   uses: Pendect/action-rsyncer@master
      #   env:
      #     DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #   with:
      #     flags: '-avzr --delete'
      #     src: 'doc-build/doc_dev/html'
      #     dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/3-master-dev'
