name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Compiler Versions
      run: |
        g++ --version; true
        cmake --version; true
        ccache --version; true
        nproc; true
    - name: Run a multi-line script
      run: |
        mkdir build
        cd build
        cmake ../test/unit
        cmake --build -j 2  .
